import * as actions from '../../state/actions'
import { generateCmdsFromActions, redux } from 'effects-as-data-redux'
import { cmds } from 'effects-as-data-universal/es5'

const autoGeneratedCmdsFromReduxActions = generateCmdsFromActions(actions)

const getLocal = (key) => {
  return {
    type: "getLocal",
    key
  };
}

const saveLocal = (key, value) => {
  return {
    type: "saveLocal",
    key,
    value
  };
}

export default {
  ...redux,
  ...autoGeneratedCmdsFromReduxActions,
  ...cmds,
  getLocal,
  saveLocal
}
